- README.md
A user landing here via NPM page or Google search might not know the context. Hence adding links to API reference and docs.
> Includes links to the API reference

- .travis.yml
- CHANGELOG.md
- README.md
- lib/api.js
- lib/razorpay.js
- lib/utils/razorpay-utils.js
- package.json
- test/mocker.js
- test/resources/orders.spec.js
- test/resources/payments.spec.js
- test/resources/refunds.spec.js
- test/utils/razorpay-utils.spec.js
Uses https://github.com/node-nock/nock for mocking the http requests
> Adds test suite

- CHANGELOG.md
- examples/index.js
- lib/resources/orders.js
- test/resources/orders.spec.js
> Adds support for fetching order's payments

- examples/index.js
- lib/utils/razorpay-utils.js
- package.json
- test/resources/orders.spec.js
- test/utils/razorpay-utils.spec.js
Don't assume `undefined` values as `0` in requests
> Remove default bool param

- examples/index.js
- lib/api.js
- lib/razorpay.js
- lib/resources/payments.js
- lib/resources/transfers.js
- test/resources/payments.spec.js
- test/resources/transfers.spec.js
Adds support for transfer and reversal operations
> Transfers and Reversals

- README.md
Add wiki link to transfers resource
> Add wiki link to transfers resource

- dist/razorpay.js
- dist/resources/addons.js
- dist/resources/payments.js
- dist/resources/plans.js
- dist/resources/subscriptions.js
- dist/resources/virtualAccounts.js
- lib/razorpay.js
- lib/resources/addons.js
- lib/resources/payments.js
- lib/resources/plans.js
- lib/resources/subscriptions.js
- lib/resources/virtualAccounts.js
- lib/utils/predefined-tests.js
- package-lock.json
- test/resources/addons.spec.js
- test/resources/payments.spec.js
- test/resources/plans.spec.js
- test/resources/subscriptions.spec.js
- test/resources/virtualAccounts.spec.js
ref https://github.com/razorpay/api/issues/5647
> Adds Virtual accounts missing api and subscriptions api

- dist/resources/payments.js
- lib/resources/payments.js
- package-lock.json
- package.json
`on_hold` is sent as `false`, due to the wrong condition
> Fixed on_hold condition in transfers

- dist/resources/virtualAccounts.js
- lib/resources/virtualAccounts.js
- package-lock.json
- package.json
Fixes: https://github.com/razorpay/razorpay-node/issues/26
> Sending generic input to api

- dist/razorpay.js
- dist/utils/razorpay-utils.js
- lib/razorpay.js
- lib/utils/razorpay-utils.js
- package-lock.json
- package.json
- test/utils/razorpay-utils.spec.js
Fixes https://github.com/razorpay/razorpay-node/issues/29
> Adds validateWebhookSignature support

- package-lock.json
- package.json
- Major upgrade to `chai`, `mocha` in devDeps
- npm audit returns zero issues now
> [deps] Update dependencies

- package-lock.json
- package.json
- This bumps extend to 3.0.2 as well, which fixes a security issue
> [deps] Bump request version

- dist/resources/addons.js
- lib/resources/addons.js
- test/resources/addons.spec.js
> Node-sdk Addon

- dist/resources/customers.js
- lib/resources/customers.js
- test/resources/customers.spec.js
> Node-sdk Customer

- dist/razorpay.js
- dist/resources/fundAccount.js
- lib/razorpay.js
- lib/resources/fundAccount.js
- test/resources/fundAccount.spec.js
> Node-sdk fundAccount

- dist/resources/paymentLink.js
- lib/resources/paymentLink.js
- test/resources/paymentLink.spec.js
> Node-sdk PaymentLink

- dist/razorpay.js
- dist/resources/qrCode.js
- lib/razorpay.js
- lib/resources/qrCode.js
- test/resources/qrCode.spec.js
> Node-sdk qrCode

- dist/resources/refunds.js
- lib/resources/refunds.js
- test/resources/refunds.spec.js
> Node-sdk refunds

- dist/razorpay.js
- dist/resources/settlements.js
- lib/razorpay.js
- lib/resources/settlements.js
- test/resources/settlements.spec.js
> Node-sdk Settlments

- dist/resources/virtualAccounts.js
- lib/resources/virtualAccounts.js
- test/resources/virtualAccounts.spec.js
added addReceiver, allowedPayer & deleteAllowedPayer functions
> Node-sdk VirtulAccount updated

- documents/customer.md
Doc reference : https://razorpay.com/docs/api/customers
> customer doc correction

- documents/fund.md
Doc reference : https://razorpay.com/docs/customers/customer-fund-account-api
> fund readme correction

- dist/resources/payments.js
- dist/resources/settlements.js
- documents/payment.md
- documents/settlement.md
- lib/resources/payments.js
- lib/resources/settlements.js
- test/resources/settlements.spec.js
Doc reference : https://razorpay.com/docs/api/payments/
fixed fetch and all for `expand[]` parameter
https://razorpay.com/docs/api/payments/#fetch-a-payment
https://razorpay.com/docs/api/payments/#fetch-multiple-payments
> Payment doc correction

- documents/subscription.md
Doc reference : https://razorpay.com/docs/api/payments/subscriptions/
> subscription doc correction

- documents/addon.md
Doc reference : https://razorpay.com/docs/payments/subscriptions/create-add-ons#related-information
> addon doc corrections

- documents/items.md
Doc reference : https://razorpay.com/docs/api/items/
> items doc corrections

- dist/api.js
- dist/resources/paymentLink.js
- documents/paymentLink.md
- lib/api.js
- lib/resources/paymentLink.js
Doc reference : https://razorpay.com/docs/api/payments/payment-links/
fixed edit payment link (faulty expire_by issue)
> paymentlink correction

- documents/qrcode.md
Doc reference : https://razorpay.com/docs/api/qr-codes
> qrcode doc correction

- documents/card.md
Doc reference : https://razorpay.com/docs/api/payments/recurring-payments/cards/create-authorization-transaction
> card doc correction

- documents/papernach.md
Doc reference : https://razorpay.com/docs/api/payments/recurring-payments/paper-nach/create-authorization-transaction/
> papernach doc correction

- documents/registerNach.md
Doc reference : https://razorpay.com/docs/api/payments/recurring-payments/paper-nach/auto-debit
> registernach doc correction

- README.md
- dist/resources/payments.js
- documents/order.md
- documents/payment.md
- documents/token.md
- lib/resources/payments.js
Doc reference : https://razorpay.com/docs/payments/third-party-validation/#step-2-create-an-order
> Third party validation

- documents/order.md
Doc reference : https://razorpay.com/docs/api/orders/#create-an-order
> order readme correction

- .github/workflows/ci.yml
- package-lock.json
- package.json
| Test Case Document URL                        |
|-----------------------------------------------|
| Please paste test case document link here.... |
> feat: add release workflow
